from time import sleep
thislist = ["apple", "banana", "cherry","pineapple"]
print("Wszystkie elementy listy: ",thislist)
print("Pierwszy element listy: ",thislist[0])
print("Drugi element listy: ",thislist[1])
print("Trzeci element listy: ",thislist[2])
print("Czwarty element listy: ",thislist[3])
for x in thislist:
  print(x.upper())
print("Dodawanie elementu listy przez Użytkownika")
add = input("Wpisz nazwę owocu lub warzywa ")
thislist.append(add)
print(thislist)
print("Czyścimy listę...")
sleep(1)
thislist.clear()
print(thislist)
first = input("Wpisz pierwszy owoc lub warzywo ")
second = input("Wpisz drugi owoc lub warzywo ")
third = input("Wpisz trzeci owoc lub warzywo ")
fourth = input("Wpisz czwarty owoc lub warzywo ")
sleep(2)
print("Dziękuję... Uzupełniam listę")
sleep(2)
thislist.append(first)
thislist.append(second)
thislist.append(third)
thislist.append(fourth)
print("Oto Twoja lista:")
for x in thislist:
    print (x)
price_first = input("Wprowadź cenę w PLN za pierwszy produkt ")
price_second = input("Wprowadź cenę w PLN za drugi produkt ")
price_third = input("Wprowadź cenę w PLN za trzeci produkt ")
price_fourth = input("Wprowadź cenę w PLN za czwarty produkt ")
print("Uzupełniam cennik...")
sleep(1)
thelist2 = []
thelist2.append(price_first)
thelist2.append(price_second)
thelist2.append(price_third)
thelist2.append(price_fourth)
thelist3 = thislist + thelist2
print("Cena za " + thislist[0] + " wynosi " + thelist2[0] + " zł/1kg")
print("Cena za " + thislist[1] + " wynosi " + thelist2[1] + " zł/kg")
print("Cena za " + thislist[2] + " wynosi " + thelist2[2] + " zł/kg")
print("Cena za " + thislist[3] + " wynosi " + thelist2[3] + " zł/kg")
print("")
print("Dziękujemy za skorzystanie z naszego sklepu i zapraszamy ponownie")
